#!/bin/sh

# Add machine-specific aliases and shell functions here

alias vim=nvim

# gcog: git checkout grep
# usage: gcog <unique-part-of-branch-name>
# runs: git checkout <branch-name>
gcog() {
  git branch | grep -m 1 $1 | xargs git checkout
}
