ZSH=$HOME/.oh-my-zsh
ZSH_THEME="drueck"

# Disable flow control commands (keeps CTRL+S from freezing everything)
stty start undef
stty stop undef

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git command-not-found asdf)

source $ZSH/oh-my-zsh.sh

export EDITOR=nvim

# load other machine specific aliases
source $HOME/.aliases

# add the ~/.bin directory to the path
PATH=$PATH:~/.bin

# set machine specific PATH, etc, here
source $HOME/.zshrc.local
